import type PocketBase from 'pocketbase'
import type { ReactivityAdapter } from './reactivity'
import type { PersistenceAdapter } from './persistence/types'

/** Minimal shape every PocketBase record shares. */
export interface BaseRecord {
  [key: string]: any
  id: string
}

/**
 * Schema map: collection name -> response record type.
 *
 * Designed to accept the `CollectionResponses` interface generated by
 * `pocketbase-typegen` directly:
 *
 * ```ts
 * import type { CollectionResponses } from './pocketbase-types'
 * const lf = createLocalFirst<CollectionResponses>({ ... })
 * ```
 */
export type SchemaDef = Record<string, BaseRecord>

/** Same shape as the PocketBase SDK's ListResult. */
export interface ListResult<T> {
  page: number
  perPage: number
  totalItems: number
  totalPages: number
  items: T[]
}

/** Subset of PocketBase list/view query options that the local engine understands. */
export interface QueryOptions {
  filter?: string
  sort?: string
  expand?: string
  fields?: string
  [key: string]: any
}

export interface ListQueryOptions extends QueryOptions {
  skipTotal?: boolean
}

export interface FullListQueryOptions extends ListQueryOptions {
  batch?: number
}

/** A realtime-style event, identical to the PocketBase SDK's RecordSubscription. */
export interface RecordSubscription<T> {
  action: 'create' | 'update' | 'delete' | string
  record: T
}

export type UnsubscribeFunc = () => Promise<void> | void

/**
 * Context handed to a conflict resolver when the same record changed both
 * locally (while offline / not yet pushed) and remotely.
 */
export interface ConflictContext<T = any> {
  collection: string
  /** Local version with un-synced changes; `null` when the record was deleted locally. */
  local: T | null
  /** Current remote version; `null` when the record was deleted remotely. */
  remote: T | null
  /** Last version both sides agreed on, when known. */
  base: T | null
}

/**
 * Return the record that should win (its content will be kept locally and
 * pushed to the server), or `null` to let the delete win / delete the record.
 * Default behavior when not configured: last-update-wins.
 */
export type ConflictResolver<T = any> = (ctx: ConflictContext<T>) => T | null | Promise<T | null>

export interface CollectionSyncConfig {
  /**
   * Optional server-side filter limiting which records are cached locally
   * (e.g. only the current user's documents). Records outside the filter are
   * treated as not existing locally.
   */
  filter?: string
  /** Page size used when pulling records from the server. Default 500. */
  batch?: number
}

export interface CollectionConfig<T = any> {
  /**
   * `true`  -> collection is mirrored into the local db; reads/queries/realtime
   *            run against the local db and work offline.
   * `false` -> all calls pass through to the remote PocketBase (default).
   */
  cache?: boolean
  /**
   * Relation fields of this collection: field name -> target collection name.
   * Required for local evaluation of `expand` and relation paths in
   * filters/sorts (e.g. `author.name = "x"`), because pocketbase-typegen
   * types carry no runtime schema.
   */
  relations?: Record<string, string>
  sync?: CollectionSyncConfig
  /** Per-collection conflict resolver; falls back to the global one, then to last-update-wins. */
  conflictResolver?: ConflictResolver<T>
}

export interface SyncErrorInfo {
  collection: string
  /** The failed pending operation, if the error happened while pushing local changes. */
  op?: { type: 'create' | 'update' | 'delete'; id: string; data?: any }
  error: unknown
}

export interface SyncStatus {
  /** Reachability of the PocketBase server as far as the client can tell. */
  online: boolean
  /** True while an initial or delta sync is running. */
  syncing: boolean
  /** Number of local changes not yet confirmed by the server. */
  pending: number
  /** Timestamp (ms) of the last fully successful sync, 0 if none yet. */
  lastSyncedAt: number
}

export interface LocalFirstConfig<S extends SchemaDef = SchemaDef> {
  /** The PocketBase SDK instance to sync with (can be the typegen `TypedPocketBase`). */
  pb: PocketBase
  /** Which collections exist and whether they are cached locally. */
  collections: { [K in keyof S & string]?: CollectionConfig<S[K]> } & Record<string, CollectionConfig>
  /** Reactivity integration (e.g. `angularReactivity` from `pocketbase-localfirst/angular`). */
  reactivity?: ReactivityAdapter
  /**
   * Where cached data + the offline write queue are persisted.
   * Defaults to IndexedDB in the browser, in-memory elsewhere.
   */
  persistence?: PersistenceAdapter | 'indexeddb' | 'localstorage' | 'memory'
  /** Storage key prefix; also change it when running several apps on one origin. Default "pblf". */
  namespace?: string
  /** Global conflict resolver (default: last-update-wins). */
  conflictResolver?: ConflictResolver
  /** Start syncing immediately on creation. Default true. */
  autoStart?: boolean
  /** How often to run a full reconcile (detects deletes missed while offline). Default 5 min, 0 disables. */
  reconcileIntervalMs?: number
  /** Poll interval for reachability checks while offline. Default 10s. */
  healthCheckIntervalMs?: number
  /** Called when pushing a queued local change fails permanently (e.g. validation error). */
  onSyncError?: (info: SyncErrorInfo) => void
}
